# Generated by Django 2.2.2 on 2019-06-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(blank=True, choices=[('M', 'MEGA Millions®'), ('P', 'POWERBALL®')], max_length=1, null=True)),
                ('numbers', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=5, null=True)),
                ('occurrence', models.IntegerField(blank=True, null=True)),
                ('count_numbers', models.IntegerField(blank=True, null=True)),
                ('count_numbers_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(auto_now=True)),
                ('client_ip', models.CharField(blank=True, max_length=25, null=True)),
                ('game', models.CharField(blank=True, choices=[('M', 'MEGA Millions®'), ('P', 'POWERBALL®')], max_length=1, null=True)),
                ('numbers', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.CharField(blank=True, choices=[('M', 'MEGA Millions®'), ('P', 'POWERBALL®')], max_length=1, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
